apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-0
  labels:
    app: web-0
spec:
  selector:
    matchLabels:
      app: web-0
  replicas: 1
  template:
    metadata:
      labels:
        app: web-0
    spec:
      containers:
        - name: echoserver
          image: ghcr.io/wzshiming/echoserver/echoserver:v0.0.1
          env:
            - name: MESSAGE
              value: "web-0"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-0
  labels:
    app: web-0
    traffic.ferryproxy.io/export: "true"
spec:
  selector:
    app: web-0
  ports:
    - name: http-8080
      port: 8080
    - name: http-80
      port: 80
      targetPort: 8080
